#!/bin/bash
cd /home/judge/git
git pull

svn up /home/judge/src
cd /home/judge/src/core
pkill -9 judged
bash make.sh
cd ../install
mysql jol< update.sql
judged

web_user=`ls -l /home/judge/src/web/include/db_info.inc.php | awk -F ' ' '{print $3}'`
mkdir /var/log/hustoj/
chown -R $web_user /var/log/hustoj
